// seed.js — inserts 200,000 fake products into the database
//
// Run after migrate:  npm run seed
//
// Performance strategy — WHY bulk inserts?
// ==========================================
// A naive loop with individual INSERT statements would make 200,000 separate
// round-trips to the database. At ~1ms network latency each, that's ~200 seconds.
//
// Instead, we build INSERT statements with 1,000 rows per query:
//   INSERT INTO products (id, name, category, price, created_at, updated_at)
//   VALUES ($1,$2,$3,$4,$5,$6), ($7,$8,$9,$10,$11,$12), ... (1000 rows)
//
// This reduces round-trips from 200,000 to 200, cutting seed time to ~10-30s.

require('dotenv').config();
const { faker } = require('@faker-js/faker');
const pool = require('../src/db');

// Fixed list of categories — realistic for an e-commerce product database.
// Using a fixed list means category filtering and indexes are useful (high cardinality
// categories with millions of rows would require different index strategies).
const CATEGORIES = [
  'Electronics',
  'Clothing',
  'Home & Garden',
  'Sports & Outdoors',
  'Books',
  'Toys & Games',
  'Health & Beauty',
  'Automotive',
  'Food & Grocery',
  'Office Supplies',
];

const TOTAL_PRODUCTS = 200_000;
const BATCH_SIZE = 1_000; // rows per INSERT statement

// Spread created_at across the past 6 months so "newest first" sorting is meaningful
// and realistic — not all rows have the same timestamp.
const SIX_MONTHS_AGO = new Date(Date.now() - 6 * 30 * 24 * 60 * 60 * 1000);
const NOW = new Date();

function randomDate(from, to) {
  const fromMs = from.getTime();
  const toMs = to.getTime();
  return new Date(fromMs + Math.random() * (toMs - fromMs));
}

function generateRow() {
  const createdAt = randomDate(SIX_MONTHS_AGO, NOW);
  return {
    name: faker.commerce.productName(),
    category: CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)],
    // Price between $1.00 and $999.99
    price: parseFloat(faker.commerce.price({ min: 1, max: 999.99, dec: 2 })),
    created_at: createdAt,
    updated_at: createdAt,
  };
}

async function seed() {
  console.log(`Seeding ${TOTAL_PRODUCTS.toLocaleString()} products in batches of ${BATCH_SIZE}...`);
  const startTime = Date.now();

  const client = await pool.connect();
  try {
    let totalInserted = 0;
    const numBatches = Math.ceil(TOTAL_PRODUCTS / BATCH_SIZE);

    for (let batch = 0; batch < numBatches; batch++) {
      const rowsInThisBatch = Math.min(BATCH_SIZE, TOTAL_PRODUCTS - totalInserted);
      const rows = [];

      for (let i = 0; i < rowsInThisBatch; i++) {
        rows.push(generateRow());
      }

      // Build a single multi-row INSERT for the entire batch.
      // Parameterized queries ($1, $2, ...) prevent SQL injection and let
      // the Postgres driver handle type coercion automatically.
      //
      // Each row contributes 5 placeholders (name, category, price, created_at, updated_at).
      // id is generated by Postgres (DEFAULT gen_random_uuid()).
      const values = [];
      const placeholders = rows.map((row, i) => {
        const base = i * 5;
        values.push(row.name, row.category, row.price, row.created_at, row.updated_at);
        return `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5})`;
      });

      await client.query(
        `INSERT INTO products (name, category, price, created_at, updated_at)
         VALUES ${placeholders.join(', ')}`,
        values
      );

      totalInserted += rowsInThisBatch;

      // Log progress every 10 batches (~10,000 rows)
      if ((batch + 1) % 10 === 0 || batch === numBatches - 1) {
        const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
        console.log(`  ${totalInserted.toLocaleString()} / ${TOTAL_PRODUCTS.toLocaleString()} inserted (${elapsed}s elapsed)`);
      }
    }

    const totalTime = ((Date.now() - startTime) / 1000).toFixed(1);
    console.log(`\nSeed complete! ${TOTAL_PRODUCTS.toLocaleString()} products inserted in ${totalTime}s.`);
  } catch (err) {
    console.error('Seeding failed:', err.message);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
